CREATE DATABASE Pets

USE Pets

CREATE TABLE Clinica (
	IdClinica INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(100) NOT NULL,
)

CREATE TABLE TipoPets(
	IdTipoPet INT PRIMARY KEY IDENTITY NOT NULL,
	Descrição VARCHAR(50),
)

CREATE TABLE Dono(
	IdDono INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(100),
)

CREATE TABLE Veterinario(
	IdVeterinario INT PRIMARY KEY IDENTITY NOT NULL,
	Identificacao VARCHAR (100),	
--FK
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
)

CREATE TABLE Raca(
	IdRaca INT PRIMARY KEY IDENTITY NOT NULL,
	Explanação VARCHAR(100),
--FK
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPets(IdTipoPet),
)

CREATE TABLE Pets(
	IdPets INT PRIMARY KEY IDENTITY NOT NULL,
	Apelido VARCHAR (50),
	DataNascimento VARCHAR(10),
--FK
	IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca),
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
)

CREATE TABLE Atendimentos(
	IdAtendimentos INT PRIMARY KEY IDENTITY NOT NULL,
	Procedimento VARCHAR (100),
	DataHora DATETIME,
--FK
	IdPets INT FOREIGN KEY REFERENCES Pets(IdPets),
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),
)

